---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    environment:
      SECRET_KEY: not-a-secret
      DEBUG: 1
      DATABASE_URL: sqlite:///db.sqlite3
    steps:
      - checkout
      - run: pipenv sync --dev
      - run: pipenv run python manage.py collectstatic --noinput
      - run: pipenv run migrate
      - run: pipenv run python manage.py test


workflows:
  version: 2
  commit:
    jobs:
      - build
