---
# See https://github.com/vsoch/docsy-jekyll/blob/master/_config.yml for
# reference.

title: Census Events documentation
author: OpenOakland
description: >-
    Documentation for the Census Events app.  Find events and resources for the
    2020 Census near you.  Residents can learn more about the first all-digital
    census through these events, even finding locations where they can get
    assistance to complete the census. Residents can search for events based on
    date, location, and language.

baseurl: "/dos-census-events"
url: "https://openoakland.github.io"

# Social
repo: "https://github.com/openoakland/dos-census-events"
github_user: "openoakland"
github_repo: "dos-census-events"
twitter: OpenOakland

# Should there be feedback buttons at the bottom of pages?
feedback: true

# Link to a privacy policy in footer, uncomment and define if wanted
# privacy: https://domain.com/privacy

# google-analytics: UA-XXXXXXXXXX
# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
# logo: "assets/img/logo/SRCC-square-red.png"
logo_pixels: 34
color: "#30638e"
# color: "#8c1515" # primary color for header, buttons

# Build settings
markdown: kramdown

# If you add tags to pages, you can link them to some external search
# If you want to disable this, comment the URL.
tag_search_endpoint: https://ask.cyberinfrastructure.org/search?q=
tag_color: primary # danger, success, warning, primary, info, secondary

accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: pretty
remote_theme: vsoch/docsy-jekyll

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
